export const models = [
    {
        "id": "allam-2-7b",
        "object": "model",
        "created": 1737672203,
        "owned_by": "SDAIA",
        "active": true,
        "context_window": 4096,
        "public_apps": null,
        "max_completion_tokens": 4096,
        "features": {
            "chat": true,
            "tools": false,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": false
        },
        "metadata": {
            "display_name": "ALLaM-2-7b",
            "release_stage": "production",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 7000,
                "tokens_per_minute": 6000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 500000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "groq/compound",
        "object": "model",
        "created": 1756949530,
        "owned_by": "Groq",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 8192,
        "features": {
            "chat": true,
            "tools": false,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": false
        },
        "metadata": {
            "display_name": "Compound",
            "release_stage": "production",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 250,
                "tokens_per_minute": 70000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 0,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "groq/compound-mini",
        "object": "model",
        "created": 1756949707,
        "owned_by": "Groq",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 8192,
        "features": {
            "chat": true,
            "tools": false,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": false
        },
        "metadata": {
            "display_name": "Compound Mini",
            "release_stage": "production",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 250,
                "tokens_per_minute": 70000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 0,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "llama-3.1-8b-instant",
        "object": "model",
        "created": 1693721698,
        "owned_by": "Meta",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 131072,
        "features": {
            "chat": true,
            "tools": true,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": true
        },
        "metadata": {
            "model_card": "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct",
            "display_name": "Llama 3.1 8B",
            "model_price": {
                "batch": {
                    "Model": "llama-3.1-8b-instant",
                    "PriceInTokens": "0.000000025",
                    "PriceOutTokens": "0.00000004",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": null
                },
                "on_demand": {
                    "Model": "llama-3.1-8b-instant",
                    "PriceInTokens": "0.00000005",
                    "PriceOutTokens": "0.00000008",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.000000025",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "production",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 14400,
                "tokens_per_minute": 6000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 500000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "llama-3.3-70b-versatile",
        "object": "model",
        "created": 1733447754,
        "owned_by": "Meta",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 32768,
        "features": {
            "chat": true,
            "tools": true,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": true
        },
        "metadata": {
            "model_card": "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct",
            "display_name": "Llama 3.3 70B",
            "model_price": {
                "batch": {
                    "Model": "llama-3.3-70b-versatile",
                    "PriceInTokens": "0.000000295",
                    "PriceOutTokens": "0.000000395",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": null
                },
                "on_demand": {
                    "Model": "llama-3.3-70b-versatile",
                    "PriceInTokens": "0.00000044",
                    "PriceOutTokens": "0.00000067",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "production",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 1000,
                "tokens_per_minute": 12000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 100000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "meta-llama/llama-4-maverick-17b-128e-instruct",
        "object": "model",
        "created": 1743877158,
        "owned_by": "Meta",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 8192,
        "features": {
            "chat": true,
            "tools": true,
            "json_mode": true,
            "max_input_images": 5,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": true
        },
        "metadata": {
            "model_card": "https://huggingface.co/meta-llama/Llama-4-Maverick-17B-128E-Instruct",
            "display_name": "Llama 4 Maverick 17B 128E",
            "image_max_bytes": 20971520,
            "model_price": {
                "batch": {
                    "Model": "meta-llama/llama-4-maverick-17b-128e-instruct",
                    "PriceInTokens": "0.000000118",
                    "PriceOutTokens": "0.000000354",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": null
                },
                "on_demand": {
                    "Model": "meta-llama/llama-4-maverick-17b-128e-instruct",
                    "PriceInTokens": "0.0000002",
                    "PriceOutTokens": "0.0000006",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.0000001",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "preview",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 1000,
                "tokens_per_minute": 6000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 500000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "meta-llama/llama-4-scout-17b-16e-instruct",
        "object": "model",
        "created": 1743874824,
        "owned_by": "Meta",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 8192,
        "features": {
            "chat": true,
            "tools": true,
            "json_mode": true,
            "max_input_images": 5,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": true
        },
        "metadata": {
            "model_card": "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct",
            "display_name": "Llama 4 Scout 17B 16E",
            "image_max_bytes": 20971520,
            "model_price": {
                "batch": {
                    "Model": "meta-llama/llama-4-scout-17b-16e-instruct",
                    "PriceInTokens": "0.000000055",
                    "PriceOutTokens": "0.00000017",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": null
                },
                "on_demand": {
                    "Model": "meta-llama/llama-4-scout-17b-16e-instruct",
                    "PriceInTokens": "0.00000011",
                    "PriceOutTokens": "0.00000034",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.000000055",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "preview",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 1000,
                "tokens_per_minute": 30000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 500000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "meta-llama/llama-guard-4-12b",
        "object": "model",
        "created": 1746743847,
        "owned_by": "Meta",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 1024,
        "features": {
            "chat": true,
            "tools": false,
            "json_mode": true,
            "max_input_images": 5,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": false
        },
        "metadata": {
            "display_name": "Llama Guard 4 12B",
            "image_max_bytes": 20971520,
            "model_price": {
                "on_demand": {
                    "Model": "meta-llama/llama-guard-4-12b",
                    "PriceInTokens": "0.0000002",
                    "PriceOutTokens": "0.0000002",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.0000001",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "production",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 14400,
                "tokens_per_minute": 15000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 500000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "meta-llama/llama-prompt-guard-2-22m",
        "object": "model",
        "created": 1748632101,
        "owned_by": "Meta",
        "active": true,
        "context_window": 512,
        "public_apps": null,
        "max_completion_tokens": 512,
        "features": {
            "chat": true,
            "tools": false,
            "json_mode": false,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": false
        },
        "metadata": {
            "display_name": "Llama Prompt Guard 2 22M",
            "model_price": {
                "on_demand": {
                    "Model": "meta-llama/llama-prompt-guard-2-22m",
                    "PriceInTokens": "0.00000003",
                    "PriceOutTokens": "0.00000003",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.000000015",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "preview",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 14400,
                "tokens_per_minute": 15000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 500000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "meta-llama/llama-prompt-guard-2-86m",
        "object": "model",
        "created": 1748632165,
        "owned_by": "Meta",
        "active": true,
        "context_window": 512,
        "public_apps": null,
        "max_completion_tokens": 512,
        "features": {
            "chat": true,
            "tools": false,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": false
        },
        "metadata": {
            "display_name": "Prompt Guard 2 86M",
            "model_price": {
                "on_demand": {
                    "Model": "meta-llama/llama-prompt-guard-2-86m",
                    "PriceInTokens": "0.00000004",
                    "PriceOutTokens": "0.00000004",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.00000002",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "preview",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 14400,
                "tokens_per_minute": 15000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 500000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "moonshotai/kimi-k2-instruct",
        "object": "model",
        "created": 1752435491,
        "owned_by": "Moonshot AI",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 16384,
        "features": {
            "chat": true,
            "tools": true,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": true
        },
        "metadata": {
            "model_card": "moonshotai/Kimi-K2-Instruct",
            "display_name": "Kimi K2 Instruct",
            "model_price": {
                "batch": {
                    "Model": "moonshotai/kimi-k2-instruct",
                    "PriceInTokens": "0.0000005",
                    "PriceOutTokens": "0.0000015",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": null
                },
                "on_demand": {
                    "Model": "moonshotai/kimi-k2-instruct",
                    "PriceInTokens": "0.000001",
                    "PriceOutTokens": "0.000003",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.0000005",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "deprecated",
            "limits": {
                "requests_per_minute": 60,
                "requests_per_day": 1000,
                "tokens_per_minute": 10000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 300000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "moonshotai/kimi-k2-instruct-0905",
        "object": "model",
        "created": 1757046093,
        "owned_by": "Moonshot AI",
        "active": true,
        "context_window": 262144,
        "public_apps": null,
        "max_completion_tokens": 16384,
        "features": {
            "chat": true,
            "tools": true,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": true
        },
        "metadata": {
            "model_card": "https://huggingface.co/moonshotai/Kimi-K2-Instruct-0905",
            "display_name": "Kimi K2 0905",
            "model_price": {
                "batch": {
                    "Model": "moonshotai/kimi-k2-instruct-0905",
                    "PriceInTokens": "0.0000005",
                    "PriceOutTokens": "0.0000015",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": null
                },
                "on_demand": {
                    "Model": "moonshotai/kimi-k2-instruct-0905",
                    "PriceInTokens": "0.000001",
                    "PriceOutTokens": "0.000003",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.0000005",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "preview",
            "limits": {
                "requests_per_minute": 60,
                "requests_per_day": 1000,
                "tokens_per_minute": 10000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 300000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "openai/gpt-oss-120b",
        "object": "model",
        "created": 1754408224,
        "owned_by": "OpenAI",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 65536,
        "features": {
            "chat": true,
            "tools": true,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": true
        },
        "metadata": {
            "model_card": "https://openai.com/index/gpt-oss-model-card",
            "display_name": "GPT OSS 120B",
            "model_price": {
                "batch": {
                    "Model": "openai/gpt-oss-120b",
                    "PriceInTokens": "0.000000075",
                    "PriceOutTokens": "0.000000375",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": null
                },
                "on_demand": {
                    "Model": "openai/gpt-oss-120b",
                    "PriceInTokens": "0.00000015",
                    "PriceOutTokens": "0.00000075",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.000000075",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "production",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 1000,
                "tokens_per_minute": 8000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 200000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "openai/gpt-oss-20b",
        "object": "model",
        "created": 1754407957,
        "owned_by": "OpenAI",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 65536,
        "features": {
            "chat": true,
            "tools": true,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": true
        },
        "metadata": {
            "model_card": "https://openai.com/index/gpt-oss-model-card",
            "display_name": "GPT OSS 20B",
            "model_price": {
                "batch": {
                    "Model": "openai/gpt-oss-20b",
                    "PriceInTokens": "0.00000005",
                    "PriceOutTokens": "0.00000025",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": null
                },
                "on_demand": {
                    "Model": "openai/gpt-oss-20b",
                    "PriceInTokens": "0.0000001",
                    "PriceOutTokens": "0.0000005",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.00000005",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "production",
            "limits": {
                "requests_per_minute": 30,
                "requests_per_day": 1000,
                "tokens_per_minute": 8000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 200000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "playai-tts",
        "object": "model",
        "created": 1740682771,
        "owned_by": "PlayAI",
        "active": true,
        "context_window": 8192,
        "public_apps": null,
        "max_completion_tokens": 8192,
        "features": {
            "chat": false,
            "tools": false,
            "json_mode": false,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": false
        },
        "metadata": {
            "display_name": "PlayAI TTS",
            "model_price": {
                "on_demand": {
                    "Model": "playai-tts",
                    "PriceInTokens": "0.00005",
                    "PriceOutTokens": null,
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.000025",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "preview",
            "limits": {
                "requests_per_minute": 10,
                "requests_per_day": 100,
                "tokens_per_minute": 1200,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 3600,
                "max_file_size": 26214400
            }
        },
        "terms_url": "https://play.ht/terms/#partner-hosted-deployment-terms",
        "is_terms_required": true,
        "is_terms_accepted": false,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "playai-tts-arabic",
        "object": "model",
        "created": 1740682783,
        "owned_by": "PlayAI",
        "active": true,
        "context_window": 8192,
        "public_apps": null,
        "max_completion_tokens": 8192,
        "features": {
            "chat": false,
            "tools": false,
            "json_mode": false,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": false
        },
        "metadata": {
            "display_name": "PlayAI TTS Arabic",
            "model_price": {
                "on_demand": {
                    "Model": "playai-tts-arabic",
                    "PriceInTokens": "0.00005",
                    "PriceOutTokens": null,
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": "0.000025",
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "preview",
            "limits": {
                "requests_per_minute": 10,
                "requests_per_day": 100,
                "tokens_per_minute": 1200,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 3600,
                "max_file_size": 26214400
            }
        },
        "terms_url": "https://play.ht/terms/#partner-hosted-deployment-terms",
        "is_terms_required": true,
        "is_terms_accepted": false,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "qwen/qwen3-32b",
        "object": "model",
        "created": 1748396646,
        "owned_by": "Alibaba Cloud",
        "active": true,
        "context_window": 131072,
        "public_apps": null,
        "max_completion_tokens": 40960,
        "features": {
            "chat": true,
            "tools": true,
            "json_mode": true,
            "max_input_images": 0,
            "transcription": false,
            "audio_translation": false,
            "is_batch_enabled": true
        },
        "metadata": {
            "model_card": "https://huggingface.co/Qwen/Qwen3-32B",
            "display_name": "Qwen3-32B",
            "model_price": {
                "batch": {
                    "Model": "qwen/qwen3-32b",
                    "PriceInTokens": "0.000000145",
                    "PriceOutTokens": "0.000000295",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": null
                },
                "on_demand": {
                    "Model": "qwen/qwen3-32b",
                    "PriceInTokens": "0.00000029",
                    "PriceOutTokens": "0.00000039",
                    "PriceAudioInSeconds": null,
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": null
                }
            },
            "release_stage": "preview",
            "limits": {
                "requests_per_minute": 60,
                "requests_per_day": 1000,
                "tokens_per_minute": 6000,
                "audio_seconds_per_hour": 1800,
                "audio_seconds_per_day": 14400,
                "tokens_per_day": 500000,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "whisper-large-v3",
        "object": "model",
        "created": 1693721698,
        "owned_by": "OpenAI",
        "active": true,
        "context_window": 448,
        "public_apps": null,
        "max_completion_tokens": 448,
        "features": {
            "chat": false,
            "tools": false,
            "json_mode": false,
            "max_input_images": 0,
            "transcription": true,
            "audio_translation": true,
            "is_batch_enabled": true
        },
        "metadata": {
            "model_card": "https://huggingface.co/openai/whisper-large-v3",
            "display_name": "Whisper",
            "audio_transcription_languages": [
                "af",
                "am",
                "ar",
                "as",
                "az",
                "ba",
                "be",
                "bg",
                "bn",
                "bo",
                "br",
                "bs",
                "ca",
                "cs",
                "cy",
                "da",
                "de",
                "el",
                "en",
                "es",
                "et",
                "eu",
                "fa",
                "fi",
                "fo",
                "fr",
                "gl",
                "gu",
                "ha",
                "haw",
                "he",
                "hi",
                "hr",
                "ht",
                "hu",
                "hy",
                "id",
                "is",
                "it",
                "ja",
                "jv",
                "ka",
                "kk",
                "km",
                "kn",
                "ko",
                "la",
                "lb",
                "ln",
                "lo",
                "lt",
                "lv",
                "mg",
                "mi",
                "mk",
                "ml",
                "mn",
                "mr",
                "ms",
                "mt",
                "my",
                "ne",
                "nl",
                "nn",
                "no",
                "oc",
                "pa",
                "pl",
                "ps",
                "pt",
                "ro",
                "ru",
                "sa",
                "sd",
                "si",
                "sk",
                "sl",
                "sn",
                "so",
                "sq",
                "sr",
                "su",
                "sv",
                "sw",
                "ta",
                "te",
                "tg",
                "th",
                "tk",
                "tl",
                "tr",
                "tt",
                "uk",
                "ur",
                "uz",
                "vi",
                "yi",
                "yo",
                "yue",
                "zh"
            ],
            "audio_translation_languages": [
                "en"
            ],
            "audio_max_bytes": 26214400,
            "model_price": {
                "batch": {
                    "Model": "whisper-large-v3",
                    "PriceInTokens": null,
                    "PriceOutTokens": null,
                    "PriceAudioInSeconds": "0.0000154166666667",
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": 10
                },
                "on_demand": {
                    "Model": "whisper-large-v3",
                    "PriceInTokens": null,
                    "PriceOutTokens": null,
                    "PriceAudioInSeconds": "0.0000166666666667",
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": 10
                }
            },
            "release_stage": "production",
            "limits": {
                "requests_per_minute": 20,
                "requests_per_day": 2000,
                "tokens_per_minute": 15000,
                "audio_seconds_per_hour": 7200,
                "audio_seconds_per_day": 28800,
                "tokens_per_day": 0,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    },
    {
        "id": "whisper-large-v3-turbo",
        "object": "model",
        "created": 1728413088,
        "owned_by": "OpenAI",
        "active": true,
        "context_window": 448,
        "public_apps": null,
        "max_completion_tokens": 448,
        "features": {
            "chat": false,
            "tools": false,
            "json_mode": false,
            "max_input_images": 0,
            "transcription": true,
            "audio_translation": false,
            "is_batch_enabled": true
        },
        "metadata": {
            "display_name": "Whisper Large V3 Turbo",
            "audio_transcription_languages": [
                "af",
                "am",
                "ar",
                "as",
                "az",
                "ba",
                "be",
                "bg",
                "bn",
                "bo",
                "br",
                "bs",
                "ca",
                "cs",
                "cy",
                "da",
                "de",
                "el",
                "en",
                "es",
                "et",
                "eu",
                "fa",
                "fi",
                "fo",
                "fr",
                "gl",
                "gu",
                "ha",
                "haw",
                "he",
                "hi",
                "hr",
                "ht",
                "hu",
                "hy",
                "id",
                "is",
                "it",
                "ja",
                "jv",
                "ka",
                "kk",
                "km",
                "kn",
                "ko",
                "la",
                "lb",
                "ln",
                "lo",
                "lt",
                "lv",
                "mg",
                "mi",
                "mk",
                "ml",
                "mn",
                "mr",
                "ms",
                "mt",
                "my",
                "ne",
                "nl",
                "nn",
                "no",
                "oc",
                "pa",
                "pl",
                "ps",
                "pt",
                "ro",
                "ru",
                "sa",
                "sd",
                "si",
                "sk",
                "sl",
                "sn",
                "so",
                "sq",
                "sr",
                "su",
                "sv",
                "sw",
                "ta",
                "te",
                "tg",
                "th",
                "tk",
                "tl",
                "tr",
                "tt",
                "uk",
                "ur",
                "uz",
                "vi",
                "yi",
                "yo",
                "yue",
                "zh"
            ],
            "audio_max_bytes": 26214400,
            "model_price": {
                "batch": {
                    "Model": "whisper-large-v3-turbo",
                    "PriceInTokens": null,
                    "PriceOutTokens": null,
                    "PriceAudioInSeconds": "0.0000055555555556",
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "batch",
                    "AudioInSecondsFloor": 10
                },
                "on_demand": {
                    "Model": "whisper-large-v3-turbo",
                    "PriceInTokens": null,
                    "PriceOutTokens": null,
                    "PriceAudioInSeconds": "0.0000055555555556",
                    "PriceInImageTokens": null,
                    "PriceInCachedTokens": null,
                    "PriceInBlock": null,
                    "PriceOutBlock": null,
                    "BuiltInTool": "",
                    "BuiltInToolPrice": null,
                    "PriceSSO": null,
                    "PriceSCIM": null,
                    "ServiceTier": "on_demand",
                    "AudioInSecondsFloor": 10
                }
            },
            "release_stage": "production",
            "limits": {
                "requests_per_minute": 20,
                "requests_per_day": 2000,
                "tokens_per_minute": 15000,
                "audio_seconds_per_hour": 7200,
                "audio_seconds_per_day": 28800,
                "tokens_per_day": 0,
                "max_file_size": 26214400
            }
        },
        "terms_url": null,
        "is_terms_required": false,
        "is_terms_accepted": null,
        "is_fine_tuned": false,
        "fine_tune_name": "",
        "can_run": true
    }
]
